//
// Droscheme - a Scheme implementation
// Copyright © 2012 Andrew Robbins
//
// This program is free software: it is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. You can redistribute it and/or modify it under the
// terms of the GNU Lesser General Public License (LGPL): <http://www.gnu.org/licenses/>.
//
// generated by gos2go from ds_error.gos
package droscheme

func _error(msg interface{}) {
	_raise(SString(msg.(string)))
}
func _raise(err Any) Any {
	panic(err)
	return _void()
}
func _void() Any {
	return SVoid{}
}
func Export_ds_error(env *Env) {
	env.registerGos(_raise)
	env.registerGos(_void)
}
