#!/bin/sh
#
# i2s is a simple transpiler from I-expressions to S-expressions
#
# This file is just a script. The main implementation can be
# found in gos2go.ss. The main documentation can be found at
# <http://andydude.github.com/droscheme/cmd/gos.html>

# BEGIN config
DIR="$(dirname $0)"
#SCHEME_SCRIPT="racket -f $DIR/common.ss -f"
SCHEME_SCRIPT="guile -s"
#SCHEME_SCRIPT="ds -f"
# END config


$SCHEME_SCRIPT $DIR/desugar.scm "$@"