//
// Droscheme - a Scheme implementation
// Copyright © 2012 Andrew Robbins
//
// This program is free software: it is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. You can redistribute it and/or modify it under the
// terms of the GNU Lesser General Public License (LGPL): <http://www.gnu.org/licenses/>.
//
// generated by gos2go from ds_string.gos
package droscheme
func _stringZKZRvector(st Any) Any {
	return _void()
}
func _stringZKZRlist(st Any) Any {
	return _vectorZKZRlist(_stringZKZRvector(st))
}
func _stringZKZRsymbol(st Any) Any {
	return Symbol{name: st.(string)}
}
func Export_ds_string(env *Env) {
	env.registerGos(_stringZKZRvector)
	env.registerGos(_stringZKZRlist)
	env.registerGos(_stringZKZRsymbol)
}
