//
// Droscheme - a Scheme implementation
// Copyright © 2012 Andrew Robbins
//
// This program is free software: it is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. You can redistribute it and/or modify it under the
// terms of the GNU Lesser General Public License (LGPL): <http://www.gnu.org/licenses/>.
//
// generated by gos2go from ds_values.gos
package droscheme
func _void() Any {
	return gVoid
}
func _voidZS(a Any) bool {
	_, ok := a.(Void)
	return ok
}
func Export_ds_values(env *Env) {
	env.registerGos(_void)
	env.registerGos(_voidZS)
}
