all:
	rm -f _go_.6
	$(MAKE) -f droscheme.mk
	rm -f _go_.6
	$(MAKE) -f droscheme-debug.mk
	rm -f _go_.6
	$(MAKE) -f droscheme-script.mk
	rm -f _go_.6

clean:
	rm -f droscheme droscheme-debug droscheme-script